classDiagram
  class Usuario {
    nombre
    apellido
    correo
    contrasena
    rol
    activo
  }
  class Organizacion {
    nombre
    direccion
    contacto
    activo
  }
  class Proyecto {
    nombre
    descripcion
    estado
    fechaInicio
    fechaFin
  }
  class Instalacion {
    nombre
    descripcion
  }
  class PlanoDePlanta {
    archivo
    escala
    anchoMetros
    altoMetros
  }
  class Medicion {
    rssi_dBm
    ssid
    bssid
    frecuencia_GHz
    canal
    coordenadaX
    coordenadaY
    fechaHora
  }
  class MapaDeCalor {
    imagenGenerada
    algoritmo
    fechaGeneracion
  }
  class ReporteIA {
    recomendaciones
    puntajeCobertura
    fechaEmision
  }

  Usuario "1" -- "0..*" Proyecto : gestiona
  Organizacion "1" -- "1..*" Proyecto : solicita
  Proyecto "1" -- "1..*" Instalacion : abarca
  Instalacion "1" -- "1" PlanoDePlanta : tiene
  Proyecto "1" -- "0..*" Medicion : contiene
  Medicion "0..*" -- "1" MapaDeCalor : origina
  MapaDeCalor "1" -- "0..1" ReporteIA : genera
