@startuml
title Velocidad esperada por Sprint (PHU planificados)
skinparam defaultTextAlignment center
skinparam backgroundColor #FAFAFA

scale 1
concise "PHU comprometidos" as PHU

@PHU
0 is "Sprint 0: 0"
1 is "Sprint 1: 29"
2 is "Sprint 2: 16"
3 is "Sprint 3: 21"
4 is "Sprint 4: 26"
5 is "Sprint 5: 42"
6 is "Sprint 6: 26"
@enduml
